version: "3.9"
name: perturba
services:
  reverse-proxy:
    image: nginx:1.27-alpine
    container_name: perturba-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: ${IMAGE}
    container_name: perturba-backend
    env_file:
      - /etc/perturba/perturba.env
    restart: unless-stopped